image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

buildJob:
  stage: build
  tags:
    - AnimeHub-Front-End
  script:
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install
    - npm run build
  artifacts:
    paths:
      - build/

deployJob:
  stage: deploy
  tags:
    - AnimeHub-Front-End
  script:
    - echo "Set deployment variables"
#    - "rm -r /web/web/*"
#    - mv build/* /web/web
    - echo "Deployment scripts"
